version: '3.9'


services:
  web:
    container_name: web
    image: samidurbar/studentweb
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 80:8000
    depends_on:
      - db

  db: 
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=studentsbd
      - POSTGRES_USER=sami
      - POSTGRES_PASSWORD=sami123456
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
